Replace code that uses get_posts() with wc_get_orders()
Automattic/woocommerce-subscriptions-core pull request #171
Opened 2022-05-18 08:56 UTC by brucealdridge

**⚠️  This PR is currently in draft and contains code for debugging & testing which is not to be used in production ⚠️** 

## Description

Custom order tables are coming to WooCommerce this year. Currently the subscriptions core library is not ready to handle these changes due to the way some of queries are done.

This PR replaces calls to `get_posts()` with a call instead to `wc_get_orders()`. Due to the way `wc_get_orders()` enables [queries on custom parameters](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support) it made sense to write a helper function to simplify these calls.

During testing, this helper function helps remap the arguments from `get_posts()` to `wc_get_orders()` and throws an error if the results between that calls are different. This will allow for testing multiple flows quickly.
Once testing is complete this function can have testing and argument remapping removed.

## Testing Flows 

1. Subscriptions listing in `wp-admin` testing the pagination and filters.
2. ...tbc
3. ...tbc

Fixes #144

2022-11-08 01:45 UTC, mattallan commented
I've made some changes to this PR:
 - Renamed new function to `wcs_get_orders_with_meta_query()`
 - Updated the new function to only use the `meta_query` filters when HPOS is not enabled (this is because the new orders table supports meta query in $args )
 - Kept the code that compares the output of this new function to the previous `get_posts()`, however, it is now hidden behind the `WCS_DEBUG` constant

2022-11-08 02:36 UTC, mattallan approved these changes
I've performed the following tests on this PR:

 - [x] Filtered the **WooCommerce > Subscriptions** table by payment method
 - [x] Filtered the **WooCommerce > Orders** table by order type (renewal & parent)
 - [x] Manually called `WCS_PayPal::get_subscriptions_by_paypal_id( 'billing_agreement_/not/exists', 'objects' )` with billing agreements that exist and don't exist
 - [x] Manually called `WCS_PayPal_Standard_IPN_Handler::get_order_id_and_key()
 - [x] Manually called `wcs_get_subscription_orders( 'ids', 'renewal' )`
 - [x] Manually called `wcs_get_subscriptions_for_order( 123, $args )
   - Some different args I tested (`order_by => start_date`, `'subscription_status' => 'cancelled'`)

While testing this I noticed that the comparison exception is always being thrown when you're querying for objects instead of just ID fields. This is because `get_posts` returned WP Post objects and wc_get_orders() returns the custom order type.

I think this is good to merge

2022-11-08 03:17 UTC, mattallan commented
> While testing this I noticed that the comparison exception is always being thrown when you're querying for objects instead of just ID fields. This is because get_posts returned WP Post objects and wc_get_orders() returns the custom order type.

To work around this, I'm thinking we change the `throw_exception` comparison to always check against a list of returned IDs returned and never objects.

2022-11-08 03:46 UTC, mattallan commented
> To work around this, I'm thinking we change the throw_exception comparison to always check against a list of returned IDs returned and never objects.

I've implemented this in [0cd7435](https://github.com/Automattic/woocommerce-subscriptions-core/pull/171/commits/0cd74351a313835f0cdd199295c6fe72b1b7a812). I retested the same as above cases and returned the `$args` in `get_order_id_and_key()` back to its original state

2022-11-08 09:44 UTC, james-allan requested changes
I had to deprecate ordering the results by `'status'` ([2e39101](https://github.com/Automattic/woocommerce-subscriptions-core/pull/171/commits/2e3910185613a50b7eeca3e8bbc6e2029260ef7a)) because WC order querying doesn't support ordering by status it only supports ordering by these keys `'ID', 'id', 'type', 'date', 'modified', 'parent'`.

2022-11-08 09:44 UTC, james-allan commented on includes/gateways/paypal/includes/class-wcs-paypal-standard-ipn-handler.php
> +			$posts = wcs_get_orders_with_meta_query(
```suggestion
			$orders = wcs_get_orders_with_meta_query(
```

2022-11-08 09:44 UTC, james-allan commented on includes/gateways/paypal/includes/class-wcs-paypal-standard-ipn-handler.php
> +				$order_id  = $posts[0]->get_id();
```suggestion
				$order_id  = $orders[0]->get_id();
```

2022-11-08 09:44 UTC, james-allan commented on includes/wcs-order-functions.php
> +	];
I was thinking about this and ideally we'd do the mapping the the reverse way. ie map new keys to the old ones and then this function wouldn't need to support accepting old post keys for ever into the future. 

This will complicate this PR where we replace `get_posts()` calls but imo it's an investment in the future that might be worth making now.

2022-11-08 12:51 UTC, james-allan commented on includes/wcs-order-functions.php
> +	];
I've started this process in [a88f1b4](https://github.com/Automattic/woocommerce-subscriptions-core/pull/171/commits/a88f1b47f86a0d76b3ae332d23221f95a788b6f0). I'll need to go through and update the remaining places in this PR where we use `wcs_get_orders_with_meta_query()` to make sure the new keys are used.

2022-11-09 04:14 UTC, james-allan approved these changes
There are 5 places in this PR where the `get_posts()` call has been replaced. 

 1. `wcs_get_subscription_orders()`
      - This function isn't widely used but I've added unit tests to cover the changes in this PR.
 2. `WCS_Admin_Post_Types::request_query()`
     - The `get_posts` call here was used to filter subscriptions by payment method. You can test this still works by going to `WooCommerce -> Subscriptions` and filter the list by manual, or a specific payment method. I've done this and it works correctly on CPT stores. This whole screen doesn't work in HPOS environments.
3. `wcs_get_subscriptions()`
     - This is a widely used function and is already covered pretty extensively with unit tests. 
4. `WCS_PayPal::get_subscriptions_by_paypal_id()`
    - I've added unit tests for this. It's a simple function that gets list of subscriptions from a specific paypal profile ID which is stored in meta. 
5. `WCS_PayPal_Standard_IPN_Handler::get_order_id_and_key()`
    -  I've added unit tests for this function too. Similar to above, its a function that fetches an order or subscription data (ID and order key) from a set of PayPal request args. 

Given I've been testing with the `get_post()` and `wc_get_orders()` compare running, and that these functions have unit test coverage I think it's safe to remove that debug code now.

2022-11-09 22:28 UTC, brucealdridge reviewed
I can't approve this PR as I created it. 
I worked through the changes and tested them throughout the lifecycle of this PR. LGTM 👍

2022-11-09 22:29 UTC, merged

2022-12-13 15:25 UTC, lkraav commented on includes/wcs-order-functions.php
> +			$query['meta_query'] = $meta; // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
This fails non-HPOS stores in some queries cases, see #346