Use supported CRUD apis to determine if subscriptions are present on store (`wcs_do_subscriptions_exist()`)
Automattic/woocommerce-subscriptions-core pull request #273
Opened 2022-11-17 02:42 UTC by haszari

Fixes #251

## Description

## How to test this PR

1. Go to …
2. Click on …

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

2022-11-17 02:44 UTC, haszari commented on includes/data-stores/class-wcs-subscription-data-store-cpt.php
> + * Subscription Data Store: Stored in CPT (posts table).
I added this to clarify: `CPT` was too similar to `COT` and it confused me for a minute 😄

2022-11-17 02:47 UTC, haszari commented on wcs-functions.php
> + * Return true if there are any subscriptions in the database (active or inactive).
Updated this comment to clarify purpose. Happy to reinstate the other details if it's useful. Reviewers please feedback to make this clear!

2022-11-17 02:49 UTC, haszari commented on wcs-functions.php
> +	$results             = wc_get_orders(
As I understand it, `wc_get_orders` will search either `wp_posts` OR HPOS `wp_orders` table, depending on current settings. I think that's all that's needed, but we might want a way to search across both tables, or search the "inactive" one.

2022-11-21 02:49 UTC, haszari commented
There's an existing unit test: `WCS_Functions_Test::test_wcs_do_subscriptions_exist`

https://github.com/Automattic/woocommerce-subscriptions-core/blob/4c6904a98016e063733610d3eb05d290a7b7a6ed/tests/unit/test-wcs-functions.php#L95-L101

Unfortunately it's failing on this branch 😢 (is passing on `trunk`) … I'm investigating.

2022-11-21 03:03 UTC, haszari commented
As far as I can tell, `WCS_Helper_Subscription::create_subscription( array( 'status' => 'active' ) );` is not creating a subscription in the database. It looks like it calls [`wcs_create_subscription`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/67a921ed93e648215e2fd2d4a36a7184a988ebdd/wcs-functions.php#L98) which calls [`WC_Subscription:save()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/67a921ed93e648215e2fd2d4a36a7184a988ebdd/wcs-functions.php#L184) so will continue investigating (printf style).

2022-11-22 04:07 UTC, james-allan requested changes
Hey @haszari.

I've left some feedback comments. 

In terms of testing. What I've done is log the query that eventually runs and making sure that it is the matches with the old query. 

For example this is the query that runs on WP Posts:


```sql
SELECT   wp_posts.ID
FROM wp_posts 
WHERE 1=1  AND wp_posts.post_type = 'shop_subscription' AND ((wp_posts.post_status = 'wc-pending' OR wp_posts.post_status = 'wc-processing' OR wp_posts.post_status = 'wc-on-hold' OR wp_posts.post_status = 'wc-completed' OR wp_posts.post_status = 'wc-cancelled' OR wp_posts.post_status = 'wc-refunded' OR wp_posts.post_status = 'wc-failed' OR wp_posts.post_status = 'wc-checkout-draft'))	
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1
```

On HPOS 
```sql
SELECT  DISTINCT wp_wc_orders.id
FROM wp_wc_orders 
WHERE 1=1 AND (wp_wc_orders.status IN ('wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed','wc-checkout-draft')) AND (wp_wc_orders.type = 'shop_subscription') 
ORDER BY wp_wc_orders.date_created_gmt
DESC LIMIT 0, 1
```

The only issue I see with these is the status condition which I've raised a comment about. 

Let me know if you'd like to hand off this PR

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> +	$subscriptions_exist = false;
```suggestion
```

This line can be removed. It isn't used before it set later to `$subscriptions_exist = count( $results ) > 0;`

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> +	$results             = wc_get_orders(
Yeah this is correct. There's no need to search across both tables, this function should resolve the underlying environment

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> + * Return true if there are any subscriptions in the database (active or inactive).
I think the original comment is a perfect candidate for needing a rewrite. It included too much context of what I imagine was the original context (displaying a "standard message" whatever that means).

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> + * Return true if there are any subscriptions in the database (active or inactive).
```suggestion
 * Returns true if there are any subscriptions in the database (active or inactive).
```

To follow [WP documentation language standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#language), the comment should be in the third-person singular format. 

So this could be as simple as plural `Returns` (see example above). Some other alternatives might be:

```php
/**
 * Checks if there are any subscriptions in the database (active or inactive).
```

```php
/**
 * Determines if there are any subscriptions in the database (active or inactive).

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> + * @return boolean $subscriptions_exist True if the store has any subscriptions.
```suggestion
 * @return bool True if the store has any subscriptions, otherwise false.
```

Per the WP documetnation standards `boolean` -> `bool` https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#phpdoc-tags

2022-11-22 04:07 UTC, james-allan commented on wcs-functions.php
> +	$results             = wc_get_orders(
The [wiki for this function](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query), explains that by default this function will query for orders/subscriptions with the `wc_get_order_statuses()` statuses. That won't work for us because subscriptions have their own unique statuses (eg `'active'`) and `wcs_do_subscriptions_exist()` use to simply check for any status whatsoever. 

The equivalent of doing that is `'status' => 'all',`

2022-11-23 01:55 UTC, haszari commented on wcs-functions.php
> + * Return true if there are any subscriptions in the database (active or inactive).
Thanks! TIL, we could link to this from our handbook or docs maybe.

2022-11-23 05:38 UTC, haszari commented on wcs-functions.php
> + * Return true if there are any subscriptions in the database (active or inactive).
Fixed up (and the bool/return doc) in bb9458df495717d29cd97d2e781a8033b6e206e4

2022-11-23 05:39 UTC, haszari commented on wcs-functions.php
> +	$results             = wc_get_orders(
Aha! That also could be why the tests are failing 🤞 

Fixed in 3b559bb23ab4d38a754311bd995c8ea96b1f7301 (and the redundant `subscriptions_exist`).

2022-11-23 05:41 UTC, haszari commented
Ready for review (though I still need to update the description). Opened up for review as tests are passing & has an initial review from @james-allan .

Will fix up description tomorrow, anyone is welcome to commandeer this PR and merge if good to go.

2022-11-23 22:26 UTC, haszari commented
Now ready for review! Keen to get this wrapped up, though (full disclosure) – I haven't done any UI testing. 

Reviewer/HPOS squad:

- Please review and test as normal. 
- Maybe convenient to test this alongside other HPOS testing.
- Let me know if this needs additional testing – happy to test before merge if necessary.
- @mattallan Your call on when to merge this – I'm keen to include in the WCPay 5.1 release if possible.

2022-11-24 00:07 UTC, james-allan approved these changes
This looks good and testing well for me. 

I've also done a strict comparison on the queries on WC 7.1 HPOS, WC 7.1 WP Posts and WC 6.8 WP Posts. 

On WP Posts environments this `wc_get_orders()` call results in the following query:
```sql
SELECT   wp_posts.ID
FROM wp_posts 
WHERE 1=1  AND wp_posts.post_type = 'shop_subscription'
			
ORDER BY wp_posts.post_date DESC
LIMIT 0, 1
```

This query is ever so slightly different from the original direct query that was in `wcs_do_subscriptions_exist()` before. The only difference is the order by, but given we're just interested if 1 subscription is returned, that's unimportant. 


On HPOS this `wc_get_orders()` call resolves down to the following query: 

```sql
SELECT  DISTINCT wp_wc_orders.id
FROM wp_wc_orders 
WHERE 1=1 AND (wp_wc_orders.type = 'shop_subscription')
ORDER BY wp_wc_orders.date_created_gmt
DESC LIMIT 0, 1
```

This query too, is essentially the same query, mapped onto order HPOS tables. 

Given these queries are correct, I'm confident all the touchpoints that use `wcs_do_subscriptions_exist()` will not be impacted by this change.

2022-11-24 00:44 UTC, mattallan commented
Thanks @haszari for these changes3! I'm going to merge this PR now on your behalf :)

2022-11-24 00:44 UTC, merged