Spread inital discount across all subs line items
Automattic/woocommerce-subscriptions-core pull request #38
Opened 2021-11-09 01:21 UTC by brucealdridge

Fixes #39

Spread initial discount across all subscriptions line items.

When an admin discounts an order prior to payment with multiple subscriptions products. The discount is applied to each subscription product rather than spread across all.

This PR fixes this by spreading the discount across all subscriptions product.

**Admin**
![image](https://user-images.githubusercontent.com/57298/140843640-7d1eb08f-9eec-481f-86d2-3ce60465b3ed.png)

**Checkout** (after w/ additional 99c off coupon)
![image](https://user-images.githubusercontent.com/57298/140843567-c64b33e4-d107-4fb3-b96d-46440b98a06a.png)

#### Testing instructions

Testing needs to be done across a range of coupon / discount types. Fixed Product, Fixed Cart, Renewal Cart, Signup Fee etc.

- [x] Fixed Product
- [ ] Fixed Cart
- [ ] Renewal Cart
- [ ] Signup Fee

2021-11-12 05:00 UTC, james-allan requested changes
Hey Bruce. I ran through a couple of tests and realised that this one might be more complicated than I first thought. 

On top of the cases I mentioned in the inline comment, if a coupon gets added to the cart in this way and then you remove the product for which the discount originally applied, you end up still getting the discount even if you removed the product it was meant to be applied too. 

eg
<img width="1098" alt="Screen Shot 2021-11-12 at 2 56 44 pm" src="https://user-images.githubusercontent.com/8490476/141412136-77e6791f-5aed-4fa1-9450-13f08b3ae40e.png">

Note that the discount applied to the [weekly product](https://d.pr/i/9qnFUC), not the monthly 1. 

Fixing that will be pretty complicated I think. I'm not sure if we would prefer to create a separate issue for that or try to tackle it.

2021-11-12 05:00 UTC, james-allan commented on includes/class-wc-subscriptions-coupon.php
> +			);
I wasn't sure if calculating the subscription total in this way was necessary so I had a look at replicating some possible scenarios. 

<img width="789" alt="Screenshot on 2021-11-12 at 14-01-39" src="https://user-images.githubusercontent.com/8490476/141407236-94a04cac-1102-4de1-a889-50d0fb2b3a3e.png">

On the cart page this total is correct:
 
<img width="1083" alt="Screen Shot 2021-11-12 at 2 03 41 pm" src="https://user-images.githubusercontent.com/8490476/141407399-a6e9fc33-e081-4aa2-99d4-2b11c223f4ad.png">

If I increase any of the line item quantities though, the discount amount goes up. eg

<img width="1095" alt="Screen Shot 2021-11-12 at 2 05 25 pm" src="https://user-images.githubusercontent.com/8490476/141407550-922d5a96-2ab5-4903-bc5c-aa9a099c8693.png">

If I add a different subscription product to the cart, the amount of discount goes down:

<img width="1089" alt="Screen Shot 2021-11-12 at 2 06 40 pm" src="https://user-images.githubusercontent.com/8490476/141408348-fcc7db9c-c1a3-4403-b317-4215622ac899.png">

I think there are two things leading to this problem.

1. When we create the pseudo coupon we set the products that the coupon applies to and match them with the items on the order. That happens here. https://github.com/automattic/woocommerce-subscriptions-core/blob/fix/37-spread-initial-discount-across-all-products/includes/class-wcs-cart-renewal.php#L1414 when I add a different product to the cart, the discount amount goes down because the discount is being spread across the total subscription subtotal, but only applies to 2 products so it's missing the last fractional calculation. So instead of adding up the total subscription subtotal, we'd need to sum the total cart value for items that the coupon applies to.
2. The first issue of the discount going up when I change the qty, I think that is just caused by a miscalculation in this `$subscription_subtotal`. Adding a `* $item['quantity']` to the end would likely fix it.

2021-11-14 21:26 UTC, brucealdridge commented on includes/class-wc-subscriptions-coupon.php
> +			);
> The first issue of the discount going up when I change the qty, I think that is just caused by a miscalculation in this `$subscription_subtotal`. Adding a `* $item['quantity']` to the end would likely fix it.

Ah, good catch. I assumed this was getting the line item value, but its just getting the line item product cost.

```php
    $item_price = ( $include_tax ? wc_get_price_including_tax( $item['data'] ) : wc_get_price_excluding_tax( $item['data'] ) );
    return $carry + ( $item_price * $item['quantity'] );
```

2021-11-14 21:28 UTC, brucealdridge commented
Looks like this issue / PR is problematic and the proposed "fix" opens more bugs. May require a rethink.

2021-11-15 21:07 UTC, haszari commented
I'm thinking we should close this – the original issue is an edge case, and any fix may result in other issues.

2021-11-16 04:03 UTC, james-allan commented
> I'm thinking we should close this 

I agree. The initial order discount coupon behaviour is more complex given customers can add to and edit their original order while it's in the cart. That can lead to incorrect discount amounts and even applying a discount to the wrong item as I mentioned in https://github.com/Automattic/woocommerce-subscriptions-core/pull/38#discussion_r747975788. 

We'll need to close this rethink how we handle discounts applied to subscription parent orders. I'll make a note on the original issue to include details about the potential gotchas here.

2021-11-16 04:03 UTC, closed without merging