Fix filtered order links in subscription reports not working correctly when HPOS is enabled
Automattic/woocommerce-subscriptions-core pull request #609
Opened 2024-04-26 05:21 UTC by Mayisha

Fixes WCS-4650
With HPOS enabled, the links highlighted in the screenshot below do not work as intended, resulting in a list of all orders instead of showing the filtered order for the reports being viewed.

![reports](https://github.com/Automattic/woocommerce-subscriptions-core/assets/33387139/803909d2-4d3d-49c6-9ea7-82c53fe6be24)

### Description
- The existing `posts_where` filter works on the `posts` table only. As this is not triggered for the HPOS order table, the orders are not filtered by expected ids when coming from the reports page.
- I have used the `woocommerce_orders_table_query_clauses` filter which is available to modify the query clauses of the HPOS order tables.

## How to test this PR

1. Enable HPOS from **WooCommerce > Settings > Advanced > Features** page.
2. Enable compatibility mode if not enabled already to view the subscription report when HPOS is enabled.
3. Go to **WooCommerce > Reporst > Subscriptions**
4. Click the link `subscription renewals`.
5. In `trunk` it should take you to the order table page and display all the orders.
6. In this branch, it should take you to the order table page and display the renewal orders only.

2024-04-29 05:14 UTC, james-allan requested changes
Hey @Mayisha I noticed there are a few PHPCS issues being flagged with this PR: 

<img width="1112" alt="Screenshot 2024-04-29 at 11 39 25 AM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/bfbdc52f-64e5-47f2-a99a-37e19ce88cf2">

I know this function you've introduced is based on the existing `filter_orders_and_subscriptions_from_list()` and I suspect that function has the same PHPCS concerns.

A couple of things about those PHPCS issues. 

**The Nonce violations** 

I'm not sure we need a nonce in this situation given the GET args in this situation. There must be a transient that matches the `_report` arg, and that transient value must have a key matching the value in `_subscriptions_list_key`. 

While that doesn't seem impossible, even if you got over that hurdle, the values inside that transient keyed value would all need to be integers otherwise they would be escaped by the `wpdb` `prepare`.

I think there might be better ways to protect this though. Ie double check that the `_report` arg is a known report type or something. 

We should also be cleaning these `$_GET` args etc.

2024-04-29 05:14 UTC, james-allan commented on includes/admin/class-wc-subscriptions-admin.php
> +		if ( ! ( isset( $_GET['page'] ) && 'wc-orders' === $_GET['page'] ) || ! isset( $_GET['_report'] ) ) {
```suggestion
		if ( ! ( isset( $_GET['page'] ) && in_array( $_GET['page'], [ 'wc-orders', 'wc-orders--shop_subscription' ] ) ) || ! isset( $_GET['_report'] ) ) {
```

The way this logic is written at the moment this function won't work on the subscriptions list table page. 

If you click on any of these subscription specific ones, you'll be redirected to the subscriptions list table with no filtering applied. The suggestion I included above should fix that. 

<img width="243" alt="Screenshot 2024-04-29 at 12 06 34 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/14733391-8d4a-46ea-8a90-0234607bf869">

2024-04-29 05:14 UTC, james-allan commented on includes/admin/class-wc-subscriptions-admin.php
> +		$clauses['where'] .= $wpdb->prepare( " AND {$wpdb->prefix}wc_orders.ID IN ($format)", $ids );
This line is throwing a couple of PHPCS errors because the prepare call has no placeholders but it does if you resolve the `$format` variable. 

WC core has similar code in a couple of places. For example the `sync_order_products()` function ([link](https://github.com/woocommerce/woocommerce/blob/1e225f701f2d21380b6e1a28b6a7cf88ad10b230/plugins/woocommerce/src/Admin/API/Reports/Products/DataStore.php#L490-L491)). ie you have to include to phpcs ignore.

2024-05-07 02:55 UTC, james-allan approved these changes

2024-05-07 02:55 UTC, james-allan commented
Changes look good. Thanks for picking this PR up @mattallan!

2024-05-08 00:02 UTC, merged

2024-06-16 17:31 UTC, WebMarketingMatters commented
Hi @mattallan @Mayisha @james-allan - Can I please confirm what version of WooCommerce subscriptions this fix is in? Looks to me like it's 7.1.0. Do you know when this will become available?
I found this bug and reported it to WooCommerce a few months ago, it would be good to finally have a fix!

2024-06-17 00:41 UTC, james-allan commented
Yep it should be 7.1.0 of `subscriptions-core`. That was included in 6.3.0 of the WooCommerce Subscriptions plugin which released back in early May.

2024-06-17 07:31 UTC, WebMarketingMatters commented
Hi @james-allan. Okay, I'm currently using 6.4.0 and the reports filtering doesn't work. It just brings up a question mark when you hover over the left-hand columns. (They should take you to the filtered/related orders for that period)
![Uploading Screenshot 2024-06-16 at 18.22.52.png…]()

2024-06-18 06:50 UTC, james-allan commented
@WebMarketingMatters your screenshot probably didn't finish uploading before you submitted your comment so I cannot see it, however, I just had a look on my local site and it's working for me. 

Are you hovering over the link indicated by the ↗︎? Like this: 
<img width="289" alt="Screenshot 2024-06-18 at 4 45 33 PM" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/2cd992b7-b821-4884-83d0-b53fb451661d">

2024-06-18 07:12 UTC, WebMarketingMatters commented
@james-allan Thanks for the reply. I have just cleared my cache and tried again and it's now working. Thanks for your help with this.