Fixes for showing/hiding other gateways express payment buttons on product pages
Automattic/woocommerce-subscriptions-core pull request #87
Opened 2022-01-10 01:16 UTC by mattallan

Fixes #81 

## Description

This PR is fixing a few issues around `get_available_payment_methods()` not being filtered on product pages. For some background, `subscriptions-core` filters this WC function to make sure only WC Payments is the only available when the cart contains a subscriptions.

On `trunk` there are two known issues caused by this area of code:
- Viewing a WC simple product with a subscription product in cart doesn't show any Stripe or PayPal express payment buttons on product page :x:
- Viewing a subscription product was incorrectly loading the Stripe and PayPal express payment buttons on the page :x:

These issue have been fixed with this PR:

- Subscription product pages don't show other gateway buttons ✅ 
- Mini-cart widget still shows other gateway buttons if the cart contains WC simple products ✅ 
![image](https://user-images.githubusercontent.com/2275145/148708605-b60c187f-228c-46b4-af25-126a2bafefad.png)

- WC simple product pages now show other gateways buttons when there's a subscription product in cart
![image](https://user-images.githubusercontent.com/2275145/148708521-2dd03a4b-5a36-477b-9ba3-5c4ec5671395.png)

## How to test this PR

1. Make sure WC Subscriptions plugin is deactivated
1. Enable WCPay Subscriptions feature
1. Install and activate the Stripe gateway
   - Enable express payment buttons
1. Install and activate the PayPal Checkout gateway (you'll have to setup a PayPal sandbox account if you don't have one yet)
   - Make sure the PayPal Buttons are being shown on product, cart, checkout and mini-cart
1. View a subscription product page and confirm no Stripe Google Pay or PayPal buttons are being shown
1. View a WC simple product page and confirm Stripe Google Pay and PayPal buttons are loading

---

Test cases I've ran:
 - Viewing a Simple Product with an empty cart 🟢
 - Viewing a Simple Product with subscription in cart 🟢
 - Viewing a Variable Product page 🟢
 - Viewing a Subscription Product page 🟢
 - Viewing a Variable Subscription page 🟢
 - Cart page with no subscription 🟢
 - Cart page with a subscription 🟢
 - Checkout page with a subscription 🟢
 - Checkout page with no subscription 🟢

## Product impact

- ✅  Added changelog entry (or does not apply)
- :x: Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- ✅  Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
  - https://github.com/Automattic/woocommerce-payments/issues/3401

2022-01-12 19:31 UTC, haszari commented
@mattallan FYI I requested review from Helix – assuming this is ready for reviews!

2022-01-13 03:01 UTC, brucealdridge commented
@mattallan is this issue/pr specifically for [PayPal Checkout](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout)? I installed it and noticed it was deprecated so tested instead with [WooCommerce PayPal Payments](https://github.com/woocommerce/woocommerce-paypal-payments/) and was able to purchase a subscription product from the mini-cart.

2022-01-13 03:34 UTC, mattallan commented
> is this issue/pr specifically for PayPal Checkout?

Yeah, this PR is specifically targetting fixes for Stripe and PayPal Checkout see https://github.com/Automattic/woocommerce-payments/issues/3401#issuecomment-999366086. Apologies that wasn't clear from the PR description 😅 


PayPal Payments doesn't check if their payment gateway is available before loading the buttons (which feels like a bug) so we/Axiom will need to patch that plugin to fix this problem.

2022-01-13 05:24 UTC, james-allan commented
This looks good to me. 

I tested the following scenarios: 

With **WC Subscriptions inactive**: 

1. Shown on WC Simple product. 👍 
2. Shown on the cart page with a simple product in the cart. 👍 
2. Shown on WC Simple product page with subscription product in the cart. 👍 
3. Not shown on the subscription product page. 👍 
4. Not shown on the subscription product page with a simple product in the cart. 👍 
3. Not shown on cart page with a subscription. 👍 

With the **WC Subscriptions plugin active**, I tested that it basically gets shown all the time in all contexts.


---

Just for completeness, I wasnt 100% convinced of the `widget_title` action handling, however, after looking at PayPal Checkout's code and looking for alternative hooks, I couldn't find anything that would work.

We could patch PayPal Checkout but we'd still have problems on old versions and that plugin has been deprecated and perhaps isn't even maintained anymore so would be a strange fix there.

2022-01-13 05:25 UTC, james-allan approved these changes

2022-01-13 05:25 UTC, james-allan requested changes
Just two tiny changes requested. :)

2022-01-13 05:25 UTC, james-allan commented on includes/gateways/class-wc-subscriptions-core-payment-gateways.php
> +	 * @since 1.4.0
```suggestion
	 * @since 1.5.0
```

2022-01-13 05:25 UTC, james-allan commented on includes/gateways/class-wc-subscriptions-core-payment-gateways.php
> +	 * @since 1.4.0
```suggestion
	 * @since 1.5.0
```

2022-01-16 23:54 UTC, mattallan commented
Thanks @james-allan and @aprea ! The latest changes/suggestions LGTM. Merging this

2022-01-16 23:54 UTC, merged

2022-01-17 20:54 UTC, shendy-a8c commented
@mattallan I see that the added changelog has [2 similar entries](https://github.com/Automattic/woocommerce-subscriptions-core/pull/87/files#diff-b40cd67182487ef24807d9c9268329d35fbd96aa2b0a9cae69e2e0d746b1c666R4-R5). Not sure if it's intentional.